
spring:
  application:
    name: Hibernate
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  data:
    jpa:
      repositories:
        enabled: true

  h2:
    console:
      enabled: true



